services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=investimento'
      - 'MYSQL_PASSWORD=Pe110306@'
      - 'MYSQL_ROOT_PASSWORD=Pe110306@'
      - 'MYSQL_USER=root'
    ports:
      - '3306'